version: "3"
services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gk
    restart: unless-stopped
  # APP*****************************************
  springbootapp:
    image: mifody777/cooperate-app:latest
    container_name: springbootapp
    ports:
      - 8081:8081
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gk
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
volumes:
  postgres-data: